### PR TITLE
Tidal Single mode

### PR DESCRIPTION
**Pull request by oscons**
Hi,

when locally collaborating (e.g. all people are in the same room) it's sometimes desirable to all work with the same instance of Tidal. While a similar effect could be achieved by muting all but one Troop client, there is still the possibility of differing Tidal and Haskell setups per client, so even if they execute the same commands, they might get different results.

This branch adds a Tidal Single mode, in which one master client starts a Tidal instance and the other clients just send commands to it and receive output from it. This in essence creates a shared Tidal session. It is possible to start two master clients, for example if you'd like to play jointly in two distant locations.

Let me know what you think about this. I'm happy to make changes if necessary.

Cheers, @oscons

### CODE REVIEW

**Comment by Qirky** [comment]
Have you tried the "no interpreter" mode? If one person starts in Tidal mode then others can use the "no interpreter" mode, which will send the commands to the user running Tidal. I think that should accomplish what you'd want? Appreciate your time and effort though!

**Comment by oscons** [comment]
Thanks for reviewing this. IMHO the "No interpreter" mode works but is just a workaround, as it has the following drawbacks:

1. There's no specific language support (e.g. comment and keyword styling) because it's using the DummyInterpreter only
2. There's no feedback from the underlying process, so you don't see error messages or other output in any of the non-playing clients

Having said that, you got me thinking and instead of making this TidalCycles only it might be worth while to make this a generic option for all supported languages.

Let me know if you'd be interested in this and I'll make the necessary changes, otherwise I'll just maintain a fork in my repo.

**Comment by Qirky** [comment]
I've implemented something in [Polyglot](https://github.com/Qirky/Polyglot) which sends console feedback to the server and forwards that information to "dummy interpreter" clients; could be added to Troop potentially as I'd rather not have lot's of language-specific features. Out of interest, what are the differences in Tidal instances that occur when all users are running tidal but all but one are muted?

**Comment by oscons** [comment]
The potential differences all boil down to state but in various different forms:

- Someone defines a (in Tidal cycles case) Haskell variable. Users who join later won't have that defined in their TidalCycles instance
- Recently ["shared variables" have been added to TidalCycles](https://forum.toplap.org/t/how-does-triggers-implementation-work-is-it-possible-to-have-patterns-react-to-each-other/492). This the same problem as above, just in a different abstraction layer. Also, these can be set through OSC from outside the Tidal interpreter as well
- If you don't share a SuperDirt session between all users (and you very very likely don't) then your SuperCollider set up might differ, e.g. in the number of orbits defined or the samples available in SuperDirt
- Last but not least you have the general problem of potential differences in software versions in Haskell, TidalCycles, SuperCollider, and SuperDirt. So code that evaluates fine in your session might actually fail in others.

While this sounds very Tidal specific, I would presume that this is potentially an issue for all other languages as well, if they run in non-shared environments (which they might very well not be, I'm not familiar enough with FoxDot or Sonic Pi).

I definitely agree with you that maintaining specific implementations for all languages is not desirable. That's why I'd offer to create a generic option that is applicable to all languages, no Tidal specifics.

With regards to Polyglot: That seems to me to be a different approach, since you're basically syncing a lot of interpreters that don't actually need to share code. To me this sounds more like a distributed instrument, in which everyone plays their voice(s) and then they all sync up to create a shared audio experience vs everyone playing the same instrument.

Apart from that, the drawback of using the DummyInterpreter is IMHO, that you don't have language specific information (formatting comments or keywords) available or functionality (like [toggling comments](https://github.com/oscons/Troop/commit/c81f4b4a63cd95c5c231fd5b011773d57d2c82e4)) would be "impossible", at least from an abstraction point of view.

_Edit: Formatting_

**Comment by Qirky** [comment]
Sorry, should have been more clear. The feature in Polyglot allows users running an interpreter (e.g. Tidal) to send their console feedback (syntax errors etc) to users who are running no interpreters. If added to Troop then any user connected with a DummyInterpreter would get information in the console. It works in the same way as your proposed changes but whoever connects first running an interpreter is automatically assigned the master (keeps the startup more generalisable). I think adding this feature and allowing dummy-interpreter users to select a syntax highlighter (so adds a drop down menu to the login ui / flag parameter) would be better as it could be used with all of the languages, which - as you say - have the same issues.

I appreciate your hard work though and your feedback. I can probably update Troop early next week with these changes.

**Comment by Qirky** [comment]
So I've added the functionality where the master client is automatically selected (first user to connect not using a dummy interpreter) and all dummy interpreters get console feedback from the master. I haven't added syntax highlighting / keyboard shortcuts  yet though but will try and do this week.

**Comment by Qirky** [comment]
Although this is closed, though I would update you that Troop now supports syntax highlighting for "no interpreter" options. So you can start one user as a master and all others as "no interpreter", selecting TidalCycles  as the syntax choice. Then all console feedback will be sent from the master to the dummy interpreters. This also works for other  languages such as FoxDot and SuperCollider too.

**Comment by oscons** [comment]
Thanks for following up @Qirky . I've implemented this very same behavior in my branch, which might now be obsolete. I'll check out your changes.

**Pull request closed without merging**
